include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.gen.dart"
    - "**.freezed.dart"
    - "bricks/app_feature/**"
    
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else

# Rules links https://dart-lang.github.io/linter/lints/