name: pssn
description: Public Safety Services in NEOM

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  app_settings: 4.2.0
  chewie: 1.4.0
  chewie_audio: 1.3.0
  crypto: 3.0.2
  dio: 5.1.0
  file_picker: 5.2.7
  firebase_analytics: 10.2.0
  firebase_core: 2.9.0
  firebase_messaging: 14.4.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.2
  flutter_facebook_auth: 5.0.8
  flutter_local_notifications: 13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.7.0
  flutter_secure_storage: 8.0.0
  flutter_web_plugins:
    sdk: flutter
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  go_router: 6.5.7
  google_sign_in: 6.1.0
  intl: 0.17.0
  json_annotation: 4.8.0
  local_auth: 2.1.6
  location: 4.4.0
  logger: 1.3.0
  provider: 6.0.5
  retrofit: 4.0.1
  shared_preferences: 2.1.0
  sign_in_with_apple: 4.3.0
  sms_autofill: 2.3.0
  twitter_login: 4.3.2

  url_launcher: 6.1.10
  video_player: 2.6.1

dev_dependencies:
  build_runner: 2.3.3
  flutter_gen_runner: 5.2.0
  flutter_launcher_icons: 0.13.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: 6.6.1
  lint: 2.0.1
  path_provider: 2.0.14
  retrofit_generator: 6.0.0+1

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/videos/

    #fonts:
    #- family: Brown
    #  fonts:
    #    - asset: assets/fonts/Brown-Thin.ttf
    #      weight: 100
    #    - asset: assets/fonts/Brown-Light.ttf
    #      weight: 300
    #    - asset: assets/fonts/Brown-Regular.ttf
    #      weight: 400
    #    - asset: assets/fonts/Brown-Bold.ttf
    #      weight: 700

