name: PR check
on:
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-check:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:3.0.0

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Pub get
        run: flutter pub get
        
      - name: build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: analyze
        run: flutter analyze

      - name: code formatting
        run: flutter format lib

      - name: code metrics
        run: flutter pub run dart_code_metrics:metrics lib --exclude="{/**.g.dart,/**.template.dart,**.freezed.dart}"

      - name: test
        run: flutter test
